/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  BrevoWebhooks: () => import('#controllers/brevo_webhooks_controller'),
  ChildProfiles: () => import('#controllers/child_profiles_controller'),
  Children: () => import('#controllers/children_controller'),
  ContactRequests: () => import('#controllers/contact_requests_controller'),
  DailyReports: () => import('#controllers/daily_reports_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  InvitationAcceptances: () => import('#controllers/invitation_acceptances_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  Legal: () => import('#controllers/legal_controller'),
  MamMedia: () => import('#controllers/mam_media_controller'),
  MamSettings: () => import('#controllers/mam_settings_controller'),
  Mfa: () => import('#controllers/mfa_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  QuickEntries: () => import('#controllers/quick_entries_controller'),
  ReportsHistory: () => import('#controllers/reports_history_controller'),
  SecuritySettings: () => import('#controllers/security_settings_controller'),
  Session: () => import('#controllers/session_controller'),
  Staff: () => import('#controllers/staff_controller'),
  SuperAdminMams: () => import('#controllers/super_admin_mams_controller'),
}
