/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'actorId',
    'createdAt',
    'id',
    'ipHash',
    'mamId',
    'metadata',
    'subjectId',
    'subjectType',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipHash: string | null
  @column()
  declare mamId: string | null
  @column()
  declare metadata: any
  @column()
  declare subjectId: string | null
  @column()
  declare subjectType: string
}

export class ChildAuthorizationSchema extends BaseModel {
  static $columns = [
    'childId',
    'createdAt',
    'decidedAt',
    'decidedBy',
    'id',
    'kind',
    'mamId',
    'notesHtml',
    'status',
    'updatedAt',
    'validFrom',
    'validUntil',
  ] as const
  $columns = ChildAuthorizationSchema.$columns
  @column()
  declare childId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare decidedAt: DateTime | null
  @column()
  declare decidedBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare mamId: string
  @column()
  declare notesHtml: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.date()
  declare validFrom: DateTime | null
  @column.date()
  declare validUntil: DateTime | null
}

export class ChildContactSchema extends BaseModel {
  static $columns = [
    'authorizedPickup',
    'childId',
    'createdAt',
    'email',
    'emergencyContact',
    'fullName',
    'id',
    'mamId',
    'notesHtml',
    'phone',
    'priority',
    'relationship',
    'updatedAt',
  ] as const
  $columns = ChildContactSchema.$columns
  @column()
  declare authorizedPickup: boolean
  @column()
  declare childId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare emergencyContact: boolean
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column()
  declare notesHtml: string | null
  @column()
  declare phone: string | null
  @column()
  declare priority: number
  @column()
  declare relationship: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ChildGuardianSchema extends BaseModel {
  static $columns = [
    'canInvite',
    'childId',
    'createdAt',
    'id',
    'mamId',
    'relationship',
    'updatedAt',
    'userId',
  ] as const
  $columns = ChildGuardianSchema.$columns
  @column()
  declare canInvite: boolean
  @column()
  declare childId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column()
  declare relationship: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ChildStaffSchema extends BaseModel {
  static $columns = ['childId', 'mamId', 'userId'] as const
  $columns = ChildStaffSchema.$columns
  @column({ isPrimary: true })
  declare childId: string
  @column()
  declare mamId: string
  @column()
  declare userId: string
}

export class ChildSchema extends BaseModel {
  static $columns = [
    'active',
    'allergies',
    'archivedAt',
    'archivedBy',
    'birthDate',
    'careEndedAt',
    'careStartedAt',
    'createdAt',
    'dietaryNotesHtml',
    'doctorName',
    'doctorPhone',
    'emergencyInstructionsHtml',
    'firstName',
    'id',
    'lastName',
    'mamId',
    'medicalNotesHtml',
    'photoKey',
    'purgeAt',
    'routinesHtml',
    'updatedAt',
  ] as const
  $columns = ChildSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare allergies: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedBy: string | null
  @column.date()
  declare birthDate: DateTime
  @column.date()
  declare careEndedAt: DateTime | null
  @column.date()
  declare careStartedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dietaryNotesHtml: string | null
  @column()
  declare doctorName: string | null
  @column()
  declare doctorPhone: string | null
  @column()
  declare emergencyInstructionsHtml: string | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string
  @column()
  declare mamId: string
  @column()
  declare medicalNotesHtml: string | null
  @column()
  declare photoKey: string | null
  @column.dateTime()
  declare purgeAt: DateTime | null
  @column()
  declare routinesHtml: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ContactRequestSchema extends BaseModel {
  static $columns = [
    'consentedAt',
    'createdAt',
    'email',
    'fullName',
    'id',
    'message',
    'organization',
    'phone',
    'role',
    'status',
    'updatedAt',
  ] as const
  $columns = ContactRequestSchema.$columns
  @column.dateTime()
  declare consentedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string
  @column()
  declare organization: string | null
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DailyEventSchema extends BaseModel {
  static $columns = [
    'childId',
    'comment',
    'createdAt',
    'createdBy',
    'endedAt',
    'id',
    'kind',
    'mamId',
    'occurredAt',
    'requestId',
    'updatedAt',
  ] as const
  $columns = DailyEventSchema.$columns
  @column()
  declare childId: string
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare mamId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare requestId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DailyReportSchema extends BaseModel {
  static $columns = [
    'activities',
    'childId',
    'createdAt',
    'createdBy',
    'diapers',
    'id',
    'mamId',
    'meals',
    'mood',
    'naps',
    'noteHtml',
    'publishedAt',
    'reportDate',
    'status',
    'temperature',
    'updatedAt',
  ] as const
  $columns = DailyReportSchema.$columns
  @column()
  declare activities: any
  @column()
  declare childId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare diapers: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column()
  declare meals: any
  @column()
  declare mood: string | null
  @column()
  declare naps: any
  @column()
  declare noteHtml: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.date()
  declare reportDate: DateTime
  @column()
  declare status: string
  @column()
  declare temperature: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HealthEntrySchema extends BaseModel {
  static $columns = [
    'authorId',
    'childId',
    'contentHtml',
    'createdAt',
    'id',
    'kind',
    'mamId',
    'updatedAt',
  ] as const
  $columns = HealthEntrySchema.$columns
  @column()
  declare authorId: string
  @column()
  declare childId: string
  @column()
  declare contentHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare mamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvitationSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'childId',
    'createdAt',
    'email',
    'expiresAt',
    'id',
    'invitedBy',
    'mamId',
    'relationship',
    'role',
    'tokenHash',
    'updatedAt',
  ] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare childId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invitedBy: string
  @column()
  declare mamId: string | null
  @column()
  declare relationship: string | null
  @column()
  declare role: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MamSchema extends BaseModel {
  static $columns = [
    'active',
    'address',
    'assignmentMode',
    'childRetentionDays',
    'createdAt',
    'description',
    'email',
    'id',
    'logoKey',
    'name',
    'phone',
    'settings',
    'slug',
    'themeKey',
    'timezone',
    'updatedAt',
  ] as const
  $columns = MamSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare address: string | null
  @column()
  declare assignmentMode: string
  @column()
  declare childRetentionDays: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoKey: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare settings: any
  @column()
  declare slug: string
  @column()
  declare themeKey: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MediaSchema extends BaseModel {
  static $columns = [
    'childId',
    'createdAt',
    'height',
    'id',
    'mamId',
    'mimeType',
    'originalName',
    'sizeBytes',
    'storageKey',
    'updatedAt',
    'uploadedBy',
    'width',
  ] as const
  $columns = MediaSchema.$columns
  @column()
  declare childId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare sizeBytes: number
  @column()
  declare storageKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedBy: string
  @column()
  declare width: number | null
}

export class MembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mamId', 'role', 'status', 'updatedAt', 'userId'] as const
  $columns = MembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class MessageSchema extends BaseModel {
  static $columns = [
    'authorId',
    'childId',
    'contentHtml',
    'createdAt',
    'id',
    'mamId',
    'updatedAt',
  ] as const
  $columns = MessageSchema.$columns
  @column()
  declare authorId: string
  @column()
  declare childId: string | null
  @column()
  declare contentHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NotificationDeliverySchema extends BaseModel {
  static $columns = [
    'actionUrl',
    'attempts',
    'body',
    'channel',
    'createdAt',
    'deliveredAt',
    'destination',
    'id',
    'lastError',
    'notificationId',
    'providerMessageId',
    'providerStatus',
    'sentAt',
    'status',
    'title',
    'updatedAt',
  ] as const
  $columns = NotificationDeliverySchema.$columns
  @column()
  declare actionUrl: string | null
  @column()
  declare attempts: number
  @column()
  declare body: string | null
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare destination: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastError: string | null
  @column()
  declare notificationId: string
  @column()
  declare providerMessageId: string | null
  @column()
  declare providerStatus: string | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NotificationPreferenceSchema extends BaseModel {
  static $columns = [
    'categorySettings',
    'createdAt',
    'emailEnabled',
    'id',
    'mamId',
    'quietHoursEnabled',
    'quietHoursEnd',
    'quietHoursStart',
    'smsEnabled',
    'updatedAt',
    'userId',
  ] as const
  $columns = NotificationPreferenceSchema.$columns
  @column()
  declare categorySettings: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailEnabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string
  @column()
  declare quietHoursEnabled: boolean
  @column()
  declare quietHoursEnd: string | null
  @column()
  declare quietHoursStart: string | null
  @column()
  declare smsEnabled: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class NotificationSchema extends BaseModel {
  static $columns = [
    'actionUrl',
    'actorId',
    'body',
    'category',
    'createdAt',
    'data',
    'id',
    'mamId',
    'readAt',
    'title',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = NotificationSchema.$columns
  @column()
  declare actionUrl: string | null
  @column()
  declare actorId: string | null
  @column()
  declare body: string | null
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mamId: string | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: string
}

export class RateLimitBucketSchema extends BaseModel {
  static $columns = [
    'action',
    'attempts',
    'blockedUntil',
    'id',
    'keyHash',
    'updatedAt',
    'windowStartedAt',
  ] as const
  $columns = RateLimitBucketSchema.$columns
  @column()
  declare action: string
  @column()
  declare attempts: number
  @column.dateTime()
  declare blockedUntil: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare windowStartedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'globalRole',
    'id',
    'lastLoginAt',
    'mfaConfirmedAt',
    'mfaEnabled',
    'mfaRecoveryCodes',
    'mfaSecret',
    'password',
    'phone',
    'phoneVerifiedAt',
    'securityVersion',
    'status',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string
  @column()
  declare globalRole: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime()
  declare mfaConfirmedAt: DateTime | null
  @column()
  declare mfaEnabled: boolean
  @column()
  declare mfaRecoveryCodes: any
  @column()
  declare mfaSecret: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column.dateTime()
  declare phoneVerifiedAt: DateTime | null
  @column()
  declare securityVersion: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
